### ISSUE TITLE
UI - View Customer Page

### ISSUE THREAD

**Issue by RafaelMeha** [estagio-2023/realestate-ui#64]
Create a new component called "view-customer" that should be opened when we open the url: http://localhost:4200/customer/view

This component should receive **only single customer data (not all customer list)** and should have more or less this format:

![Image](https://github.com/estagio-2023/realestate-ui/assets/154329717/062e803d-0f75-4309-897a-4ad819935fb8)

The image should be the same for all customers for now.
Replace the fields with the ones that we save in our database.

In the end of the page, there should be a Grey button called "Back".
If we press Back button we should get back to Customers list page.

**Comment by Silva096** [comment]
https://angular.io/guide/inputs-outputs
